### ISSUE TITLE
Removing log/ from the repo and history to avoid large files download and add log/ in the .gitignore file

### ISSUE THREAD

**Issue by xdevroey** [STAMP-project/evosuite-model-seeding-empirical-evaluation#2]

**Comment by pderakhshanfar** [comment]
- Logs are all removed and archived in the surfdrive (https://surfdrive.surf.nl/files/index.php/s/FBuhbBmJsvkiXdA)

`log/` directory has been added to `.gitignore` file (da0306a9d457f387ab071518e50f3158820288d9)
